### ISSUE TITLE
[FEAT] Center the main text + contact card on landing page

### ISSUE THREAD

**Issue by CoderHahs** [Software-For-Love/software-for-love-coming-soon#7]
Straightforward, the title pretty much explains it.

This one might be tricky, so if you need help don't hesitate to ask.

**Comment by kandloic** [comment]
Hey, I’ve been having trouble implementing the email form. As for the text alignment, I was able to center the main text but I wasn't able to keep the title and description left-aligned. I was wondering if you could help. Thanks.

**Comment by kandloic** [comment]
<img width="1440" alt="Screen Shot 2020-06-19 at 3 36 50 PM" src="https://user-images.githubusercontent.com/55165891/85174198-e521ba80-b242-11ea-8726-0b5ec3fbac40.png">
