### ISSUE TITLE
[FEAT] Footer design + Implementation

### ISSUE THREAD

**Issue by CoderHahs** [Software-For-Love/software-for-love-coming-soon#8]
This one is all up to you guys. Either you can change the footer based on what you guys like or choose to remove it all together.

**Comment by AvaneeshM** [comment]
I have implemented the footer based on the design. The icons are fully functional and redirect the user to the respective social page. I also added the logo on the bottom left but its just a placeholder for now.

**Comment by AvaneeshM** [comment]
Update: Made changes from feedback and changed the positioning of the icons. Also added the title to the center text.
